### ISSUE TITLE
Create organization keeps spinning without proceeding forward.

### ISSUE THREAD

**Issue by epsilon-0** [dani-garcia/bw_web_builds#80] opened 2022-09-14 18:57 UTC
Unable to create organization on the 2022.9.0 version of the web vault. 
Vaultwarden version 1.25.2
OS: OpenBSD (latest snapshot)

![Screenshot 2022-09-14 145527](https://user-images.githubusercontent.com/8932410/190239529-e093a595-9fac-4911-9c32-9d9a367c7bdf.png)

**Comment by BlackDex** [comment] 2022-09-14 19:09
Duplicate of https://github.com/dani-garcia/vaultwarden/issues/2737
Already fixed in latest `testing` tagged images.

**Closed by BlackDex** 2022-09-14 19:09 UTC

**Comment by epsilon-0** [comment] 2022-09-14 20:16
thank you!
